services:
  frontend:
    build: ./frontend
    container_name: truetag_frontend
    restart: always

  backend:
    build: ./backend
    container_name: truetag_backend
    restart: always
    env_file:
      - ./backend/.env

  caddy:
    image: caddy:2
    container_name: truetag_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config: